from common import *


def build():
    s = start("hub", "The map of this vault: what lazytree is, where it stands, and which page explains what. Start here.")
    # what is it
    section(s, 0, 240, "What is lazytree?", "gray", 1700)
    s.image(0, 310, 1000, 500, "split-dark.png", link=link("ui"))
    s.text(1040, 310, "A terminal UI for exploring Git history.", size=26, font=F_TITLE, color=PAL["blue"][0])
    s.text(1040, 360,
           "It draws the real shape of a repository: every\n"
           "branch as a coloured lane, merges as connectors,\n"
           "refs as labels. Move the cursor and the selected\n"
           "commit's details and syntax-highlighted diff\n"
           "follow along on the right.\n\n"
           "It is read-only: it never changes your repository.\n"
           "Keyboard first, mouse friendly, fast on 100k+\n"
           "commit repositories, readable in light and dark\n"
           "terminals.", size=18)
    y = 640
    for i, (lab, col) in enumerate([("Go 1.26", "blue"), ("Bubble Tea", "purple"), ("~7k lines", "gray"),
                                     ("15 test files", "yellow"), ("Linux + macOS", "green"), ("pre-1.0", "orange")]):
        s.chip(1040 + (i % 3) * 210, y + (i // 3) * 52, lab, col)
    s.note(1040, 760, 640, "Click the screenshot to open the UI Guide, or any\ncard below to open that page (Ctrl/Cmd-click in Obsidian).", "info")

    # status strip
    y = 880
    section(s, 0, y, "Where the project stands", "gray", 1700, "Six milestones; five are done, the last one only needs the v0.1.0 tag.")
    ms = [("M1", "Robustness", "done"), ("M2", "Performance", "done"), ("M3", "Understand a commit", "done"),
          ("M4", "Navigate & search", "done"), ("M5", "Actions & config", "done"), ("M6", "Ship it", "almost")]
    for i, (m, lab, st) in enumerate(ms):
        col = "green" if st == "done" else "yellow"
        x = i * 284
        b = s.rect(x, y + 90, 264, 110, col, strong=True, link=link("roadmap"))
        s.text(x + 16, y + 102, f"{m}  {'✅' if st == 'done' else '⏳'}", size=26, color=PAL[col][0], font=F_TITLE)
        s.text(x + 16, y + 146, lab + ("" if st == "done" else "\n(tag + upload left)"), size=16)
        if i < 5:
            s.line([(x + 264, y + 145), (x + 284, y + 145)], color=PAL["gray"][0], arrow=True)

    # page map
    y = 1130
    section(s, 0, y, "Read in this order", "gray", 1700, "Each card is a page. Numbers give the suggested reading order for a newcomer.")
    desc = {
        "vision": "Why lazytree exists, who it is for,\nwhat it deliberately does NOT do.",
        "ui": "Every part of the screen, the modes,\nthe keyboard map and the layouts.",
        "arch": "Packages, dependency rules and\nwhat every Go file is for.",
        "model": "The data types: commits, refs,\ngraph nodes and parsed diffs.",
        "runtime": "How messages flow: loading, diffs,\nbackground fetch, guards against\nstale results.",
        "graph": "The lane algorithm, step by step,\nwith a worked example.",
        "search": "In-memory search vs git-powered\nsearch, jumping, parents and HEAD.",
        "design": "The important decisions, why they\nwere made and their trade-offs.",
        "config": "Every config option, key and colour\nname, and how errors are reported.",
        "testing": "Test map, Docker matrix, macOS\nemulation, performance check.",
        "release": "Local-only release flow, release\nnotes, screenshots, Makefile.",
        "roadmap": "Milestones M1–M6 with every task.",
        "risks": "Known gaps, limits and what is\ndeliberately out of scope.",
        "glossary": "Git, TUI and project terms\nexplained in plain words.",
    }
    for i, key in enumerate(READING):
        name, label, icon, color = PAGES[key]
        x = (i % 4) * 430
        yy = y + 100 + (i // 4) * 200
        c = s.card(x, yy, 400, f"{i + 1}. {label}", desc[key], color, icon, link=link(key), min_h=170, body_size=15)

    y = y + 100 + 4 * 200 + 20
    section(s, 0, y, "How this vault is maintained", "gray", 1700)
    s.note(0, y + 80, 820, "The pages are generated by scripts/vault (Python). Edit the page\nsource there and run `make vault`, so the drawings stay consistent.\nHand edits in Obsidian are overwritten by the next build.", "warn", title="Pages are generated")
    s.note(880, y + 80, 820, "When a task is finished or a bug fixed, update the matching page\n(Roadmap, Status & Risks, and whatever page describes the area)\nin the same change as the code.", "tip", title="Keep it in step with the code")
    return s
